import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        "charcoal-border": 'var(--color-charcoal-border)',
        charcoal_border: 'var(--color-charcoal-border)',
        error: 'var(--color-error)',
        "error-red": 'var(--color-error-red)',
        error_red: 'var(--color-error-red)',
        error_container: 'var(--color-error-container)',
        "glass-fill": 'var(--color-glass-fill)',
        glass_fill: 'var(--color-glass-fill)',
        inverse_on_surface: 'var(--color-inverse-on-surface)',
        inverse_primary: 'var(--color-inverse-primary)',
        inverse_surface: 'var(--color-inverse-surface)',
        on_background: 'var(--color-on-background)',
        on_error: 'var(--color-on-error)',
        on_error_container: 'var(--color-on-error-container)',
        on_primary: 'var(--color-on-primary)',
        on_primary_container: 'var(--color-on-primary-container)',
        on_primary_fixed: 'var(--color-on-primary-fixed)',
        on_primary_fixed_variant: 'var(--color-on-primary-fixed-variant)',
        on_secondary: 'var(--color-on-secondary)',
        on_secondary_container: 'var(--color-on-secondary-container)',
        on_secondary_fixed: 'var(--color-on-secondary-fixed)',
        on_secondary_fixed_variant: 'var(--color-on-secondary-fixed-variant)',
        on_surface: 'var(--color-on-surface)',
        on_surface_variant: 'var(--color-on-surface-variant)',
        on_tertiary: 'var(--color-on-tertiary)',
        on_tertiary_container: 'var(--color-on-tertiary-container)',
        on_tertiary_fixed: 'var(--color-on-tertiary-fixed)',
        on_tertiary_fixed_variant: 'var(--color-on-tertiary-fixed-variant)',
        outline: 'var(--color-outline)',
        outline_variant: 'var(--color-outline-variant)',
        primary: 'var(--color-primary)',
        primary_container: 'var(--color-primary-container)',
        primary_fixed: 'var(--color-primary-fixed)',
        primary_fixed_dim: 'var(--color-primary-fixed-dim)',
        secondary: 'var(--color-secondary)',
        secondary_container: 'var(--color-secondary-container)',
        secondary_fixed: 'var(--color-secondary-fixed)',
        secondary_fixed_dim: 'var(--color-secondary-fixed-dim)',
        "slate-surface": 'var(--color-slate-surface)',
        slate_surface: 'var(--color-slate-surface)',
        "success-green": 'var(--color-success-green)',
        success_green: 'var(--color-success-green)',
        surface: 'var(--color-surface)',
        surface_bright: 'var(--color-surface-bright)',
        surface_container: 'var(--color-surface-container)',
        surface_container_high: 'var(--color-surface-container-high)',
        surface_container_highest: 'var(--color-surface-container-highest)',
        surface_container_low: 'var(--color-surface-container-low)',
        surface_container_lowest: 'var(--color-surface-container-lowest)',
        surface_dim: 'var(--color-surface-dim)',
        surface_tint: 'var(--color-surface-tint)',
        surface_variant: 'var(--color-surface-variant)',
        tertiary: 'var(--color-tertiary)',
        tertiary_container: 'var(--color-tertiary-container)',
        tertiary_fixed: 'var(--color-tertiary-fixed)',
        tertiary_fixed_dim: 'var(--color-tertiary-fixed-dim)',
        warning_yellow: 'var(--color-warning-yellow)',
      },
      fontFamily: {
        jakarta: ['var(--font-jakarta)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
        mono: ['var(--font-jetbrains)', 'monospace'],
      },
      borderRadius: {
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
      },
      boxShadow: {
        'blue': '0 4px 24px rgba(27,79,216,0.12)',
      },
      keyframes: {
        'scan': {
          '0%, 100%': { top: '0%' },
          '50%': { top: '100%' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 0 var(--color-primary)' },
          '50%': { boxShadow: '0 0 0 8px transparent' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'slide-in-from-right': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'zoom-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'slide-in-from-bottom': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-from-left': {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-in-from-top': {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'bounce-in': {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.08)' },
          '70%': { transform: 'scale(0.95)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'ripple': {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        'shimmer-card': {
          '0%': { backgroundPosition: '-200px 0' },
          '100%': { backgroundPosition: '200px 0' },
        },
      },
      animation: {
        'scan': 'scan 2s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'slide-in-from-right': 'slide-in-from-right 0.3s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'zoom-in': 'zoom-in 0.2s ease-out',
        'slide-in-from-bottom': 'slide-in-from-bottom 0.3s ease-out',
        'slide-in-from-left': 'slide-in-from-left 0.3s ease-out',
        'slide-in-from-top': 'slide-in-from-top 0.3s ease-out',
        'scale-in': 'scale-in 0.3s ease-out',
        'bounce-in': 'bounce-in 0.5s ease-out',
        'spin-slow': 'spin-slow 3s linear infinite',
        'float': 'float 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
export default config;
