import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#111316",
        "charcoal-border": "#2D343F",
        "charcoal_border": "#2D343F",
        "error": "#ffb4ab",
        "error-red": "#E53935",
        "error_red": "#E53935",
        "error_container": "#93000a",
        "glass-fill": "rgba(255, 255, 255, 0.05)",
        "glass_fill": "rgba(255, 255, 255, 0.05)",
        "inverse_on_surface": "#2f3034",
        "inverse_primary": "#006c53",
        "inverse_surface": "#e2e2e6",
        "on_background": "#e2e2e6",
        "on_error": "#690005",
        "on_error_container": "#ffdad6",
        "on_primary": "#00382a",
        "on_primary_container": "#a4ffdd",
        "on_primary_fixed": "#002117",
        "on_primary_fixed_variant": "#00513d",
        "on_secondary": "#68000c",
        "on_secondary_container": "#ffd2ce",
        "on_secondary_fixed": "#410004",
        "on_secondary_fixed_variant": "#930015",
        "on_surface": "#e2e2e6",
        "on_surface_variant": "#bdc9c2",
        "on_tertiary": "#3b2f00",
        "on_tertiary_container": "#4d3e00",
        "on_tertiary_fixed": "#231b00",
        "on_tertiary_fixed_variant": "#554500",
        "outline": "#88938d",
        "outline_variant": "#3e4944",
        "primary": "#79d8b7",
        "primary_container": "#007a5e",
        "primary_fixed": "#95f5d2",
        "primary_fixed_dim": "#79d8b7",
        "secondary": "#ffb3ae",
        "secondary_container": "#c40220",
        "secondary_fixed": "#ffdad7",
        "secondary_fixed_dim": "#ffb3ae",
        "slate-surface": "#1E2229",
        "slate_surface": "#1E2229",
        "success-green": "#00A37D",
        "success_green": "#00A37D",
        "surface": "#111316",
        "surface_bright": "#37393d",
        "surface_container": "#1e2023",
        "surface_container_high": "#282a2d",
        "surface_container_highest": "#333538",
        "surface_container_low": "#1a1c1f",
        "surface_container_lowest": "#0c0e11",
        "surface_dim": "#111316",
        "surface_tint": "#79d8b7",
        "surface_variant": "#333538",
        "tertiary": "#ecc300",
        "tertiary_container": "#cba800",
        "tertiary_fixed": "#ffe17b",
        "tertiary_fixed_dim": "#ecc300",
        "warning_yellow": "#FFD54F",
      },
      fontFamily: {
        jakarta: ['var(--font-jakarta)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
        mono: ['var(--font-jetbrains)', 'monospace'],
      },
      borderRadius: {
        xl: '12px',
        '2xl': '16px',
      },
      boxShadow: {
        'blue': '0 4px 24px rgba(27,79,216,0.12)',
      }
    },
  },
  plugins: [],
};
export default config;
